"""autoincrement3

Revision ID: 06490a098444
Revises: 96691d29c9c7
Create Date: 2024-01-03 15:10:38.707480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06490a098444'
down_revision = '96691d29c9c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interventions_values', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hashtag', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interventions_values', schema=None) as batch_op:
        batch_op.drop_column('hashtag')

    # ### end Alembic commands ###
