"""config_text template_text

Revision ID: 0c53d5019d2f
Revises: 0e63d143d8a4
Create Date: 2024-01-19 15:49:07.021597

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0c53d5019d2f'
down_revision = '0e63d143d8a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interventions_values', schema=None) as batch_op:
        batch_op.add_column(sa.Column('template_text', sa.Text(), nullable=True))
        batch_op.drop_column('config_text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interventions_values', schema=None) as batch_op:
        batch_op.add_column(sa.Column('config_text', mysql.TEXT(), nullable=True))
        batch_op.drop_column('template_text')

    # ### end Alembic commands ###
