"""photo low res

Revision ID: 0e2beb5e54ba
Revises: 5aa261e9dcd5
Create Date: 2024-02-21 18:25:11.158120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e2beb5e54ba'
down_revision = '5aa261e9dcd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename_lowres', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.drop_column('filename_lowres')

    # ### end Alembic commands ###
