"""update table events

Revision ID: 1b7a5b620611
Revises: dd940d020386
Create Date: 2024-03-13 19:28:31.342849

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1b7a5b620611'
down_revision = 'dd940d020386'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('object', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('object_id', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('action', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('value_before', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('value_after', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('datetime_notification_sent', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('datetime_notification_read', sa.DateTime(timezone=True), nullable=True))
        batch_op.drop_index('event_on_site_uuid')
        batch_op.create_index(batch_op.f('ix_events_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_description'), ['description'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_object'), ['object'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_object_id'), ['object_id'], unique=False)
        batch_op.drop_column('event_on_site_uuid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_on_site_uuid', mysql.VARCHAR(length=36), nullable=True))
        batch_op.drop_index(batch_op.f('ix_events_object_id'))
        batch_op.drop_index(batch_op.f('ix_events_object'))
        batch_op.drop_index(batch_op.f('ix_events_description'))
        batch_op.drop_index(batch_op.f('ix_events_action'))
        batch_op.create_index('event_on_site_uuid', ['event_on_site_uuid'], unique=False)
        batch_op.drop_column('datetime_notification_read')
        batch_op.drop_column('datetime_notification_sent')
        batch_op.drop_column('description')
        batch_op.drop_column('value_after')
        batch_op.drop_column('value_before')
        batch_op.drop_column('action')
        batch_op.drop_column('object_id')
        batch_op.drop_column('object')

    # ### end Alembic commands ###
