"""intervention_values 3

Revision ID: 1e4e279e020a
Revises: 7b72161e2ce7
Create Date: 2024-01-02 14:56:35.457742

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1e4e279e020a'
down_revision = '7b72161e2ce7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interventions', schema=None) as batch_op:
        batch_op.drop_constraint('interventions_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('interventions_ibfk_3', type_='foreignkey')
        batch_op.drop_column('organization_id')
        batch_op.drop_column('version')
        batch_op.drop_column('place_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interventions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('place_id', mysql.VARCHAR(length=36), nullable=True))
        batch_op.add_column(sa.Column('version', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('organization_id', mysql.VARCHAR(length=36), nullable=True))
        batch_op.create_foreign_key('interventions_ibfk_3', 'organizations', ['organization_id'], ['id'])
        batch_op.create_foreign_key('interventions_ibfk_1', 'places', ['place_id'], ['id'])

    # ### end Alembic commands ###
