"""refactoring

Revision ID: 1e74162ee2d0
Revises: f86bd8e82086
Create Date: 2023-12-31 00:20:00.101960

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1e74162ee2d0'
down_revision = 'f86bd8e82086'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.drop_index('ix_fields_form_on_site_uuid')
        batch_op.drop_column('form_on_site_uuid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('form_on_site_uuid', mysql.VARCHAR(length=36), nullable=True))
        batch_op.create_index('ix_fields_form_on_site_uuid', ['form_on_site_uuid'], unique=False)

    # ### end Alembic commands ###
