"""json dans places

Revision ID: 25e12ad7aee0
Revises: 
Create Date: 2024-03-04 09:43:19.583815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25e12ad7aee0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.drop_index('places_place_json_IDX')
        batch_op.create_index(batch_op.f('ix_places_place_json'), ['place_json'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_places_place_json'))
        batch_op.create_index('places_place_json_IDX', ['place_json'], unique=False)

    # ### end Alembic commands ###
