"""intervention_values S

Revision ID: 3707b5f2d29e
Revises: 94c047c2a912
Create Date: 2024-01-02 15:32:48.715043

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3707b5f2d29e'
down_revision = '94c047c2a912'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interventions_values', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intervention_values_on_site_uuid', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_interventions_values_intervention_values_on_site_uuid'), ['intervention_values_on_site_uuid'], unique=False)
        batch_op.drop_constraint('interventions_values_ibfk_1', type_='foreignkey')
        batch_op.drop_column('intervention_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interventions_values', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intervention_id', mysql.VARCHAR(length=36), nullable=True))
        batch_op.create_foreign_key('interventions_values_ibfk_1', 'interventions', ['intervention_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_interventions_values_intervention_values_on_site_uuid'))
        batch_op.drop_column('intervention_values_on_site_uuid')

    # ### end Alembic commands ###
