"""autoincrement4

Revision ID: 3f3aaf5a84f3
Revises: 06490a098444
Create Date: 2024-01-03 15:18:00.105776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f3aaf5a84f3'
down_revision = '06490a098444'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interventions_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interventions_values_hashtag'), ['hashtag'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interventions_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interventions_values_hashtag'))

    # ### end Alembic commands ###
