"""assignee user

Revision ID: 5aa261e9dcd5
Revises: bd1b2f42ca42
Create Date: 2024-02-20 18:45:12.319734

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5aa261e9dcd5'
down_revision = 'bd1b2f42ca42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interventions_values', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assignee_user_id', sa.String(length=36), nullable=True))
        batch_op.drop_constraint('interventions_values_ibfk_4', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['assignee_user_id'], ['id'])
        batch_op.drop_column('supervisor_user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interventions_values', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supervisor_user_id', mysql.VARCHAR(length=36), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('interventions_values_ibfk_4', 'users', ['supervisor_user_id'], ['id'])
        batch_op.drop_column('assignee_user_id')

    # ### end Alembic commands ###
