"""virer template_text de interventionsvalues

Revision ID: 6ed9a8709930
Revises: ea1903bf5260
Create Date: 2024-03-03 19:28:57.947441

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6ed9a8709930'
down_revision = 'ea1903bf5260'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interventions_values', schema=None) as batch_op:
        batch_op.drop_index('ix_interventions_values_intervention_values_on_site_uuid')
        batch_op.create_index(batch_op.f('ix_interventions_values_intervention_values_on_site_uuid'), ['intervention_values_on_site_uuid'], unique=True)
        batch_op.drop_column('template_text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interventions_values', schema=None) as batch_op:
        batch_op.add_column(sa.Column('template_text', mysql.TEXT(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_interventions_values_intervention_values_on_site_uuid'))
        batch_op.create_index('ix_interventions_values_intervention_values_on_site_uuid', ['intervention_values_on_site_uuid'], unique=False)

    # ### end Alembic commands ###
