"""photo intervention_values_on_site_uuid

Revision ID: 7636d6cc574c
Revises: ec7ec5e04a71
Create Date: 2024-03-08 20:54:15.990515

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7636d6cc574c'
down_revision = 'ec7ec5e04a71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intervention_values_on_site_uuid', sa.String(length=36), nullable=True))
        batch_op.drop_index('ix_photos_intervention_on_site_uuid')
        batch_op.create_index(batch_op.f('ix_photos_intervention_values_on_site_uuid'), ['intervention_values_on_site_uuid'], unique=False)
        batch_op.drop_column('intervention_on_site_uuid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intervention_on_site_uuid', mysql.VARCHAR(length=36), nullable=True))
        batch_op.drop_index(batch_op.f('ix_photos_intervention_values_on_site_uuid'))
        batch_op.create_index('ix_photos_intervention_on_site_uuid', ['intervention_on_site_uuid'], unique=False)
        batch_op.drop_column('intervention_values_on_site_uuid')

    # ### end Alembic commands ###
