"""num_chrono et indice pour interventionsvalues

Revision ID: 7a8164529669
Revises: 25e12ad7aee0
Create Date: 2024-03-04 15:18:06.708171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a8164529669'
down_revision = '25e12ad7aee0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interventions_values', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_chrono', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('indice', sa.String(length=2), nullable=True))
        batch_op.create_index(batch_op.f('ix_interventions_values_num_chrono'), ['num_chrono'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interventions_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interventions_values_num_chrono'))
        batch_op.drop_column('indice')
        batch_op.drop_column('num_chrono')

    # ### end Alembic commands ###
