"""photo full size

Revision ID: 7e4fe993cd48
Revises: 0e2beb5e54ba
Create Date: 2024-02-22 10:14:43.958389

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7e4fe993cd48'
down_revision = '0e2beb5e54ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename_fullsize', sa.String(length=255), nullable=True))
        batch_op.drop_column('filename_lowres')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename_lowres', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('filename_fullsize')

    # ### end Alembic commands ###
