"""dict_of_lists_for_places

Revision ID: 8f8a84aa4229
Revises: 7e4fe993cd48
Create Date: 2024-02-25 20:05:31.896387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f8a84aa4229'
down_revision = '7e4fe993cd48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dict_of_lists_for_places', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_column('dict_of_lists_for_places')

    # ### end Alembic commands ###
