"""autoincrement2

Revision ID: 96691d29c9c7
Revises: 3707b5f2d29e
Create Date: 2024-01-03 14:49:20.732812

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '96691d29c9c7'
down_revision = '3707b5f2d29e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interventions_values', schema=None) as batch_op:
        batch_op.drop_column('hashtag')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interventions_values', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hashtag', mysql.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
