"""supervisor_user

Revision ID: 9a5454753480
Revises: 3f3aaf5a84f3
Create Date: 2024-01-04 19:07:11.159156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a5454753480'
down_revision = '3f3aaf5a84f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interventions_values', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supervisor_user_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['supervisor_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interventions_values', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('supervisor_user_id')

    # ### end Alembic commands ###
