"""deplacement field_value

Revision ID: a90cc60ad18d
Revises: 1e74162ee2d0
Create Date: 2024-01-02 10:56:15.561651

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a90cc60ad18d'
down_revision = '1e74162ee2d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.drop_index('ix_fields_field_value')
        batch_op.drop_column('field_value')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('field_value', mysql.VARCHAR(length=255), nullable=True))
        batch_op.create_index('ix_fields_field_value', ['field_value'], unique=False)

    # ### end Alembic commands ###
