"""Initial migration 2

Revision ID: bd1b2f42ca42
Revises: f2c750563fb9
Create Date: 2024-02-19 16:01:05.059386

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bd1b2f42ca42'
down_revision = 'f2c750563fb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('field_type', sa.String(length=100), nullable=True))
        batch_op.drop_column('type_field')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_field', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('field_type')

    # ### end Alembic commands ###
