"""fields values

Revision ID: d0dd98c67b4e
Revises: f2117fffebb9
Create Date: 2024-01-26 09:48:30.573907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0dd98c67b4e'
down_revision = 'f2117fffebb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field_values',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_user_id', sa.String(length=36), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('intervention_values_id', sa.String(length=36), nullable=True),
    sa.Column('field_id', sa.String(length=36), nullable=True),
    sa.Column('field_on_site_uuid', sa.String(length=36), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.ForeignKeyConstraint(['intervention_values_id'], ['interventions_values.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('field_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_field_values_field_on_site_uuid'), ['field_on_site_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_field_values_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_field_values_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_field_values_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('field_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_field_values_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_field_values_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_field_values_name'))
        batch_op.drop_index(batch_op.f('ix_field_values_field_on_site_uuid'))

    op.drop_table('field_values')
    # ### end Alembic commands ###
