"""add version in interventions table

Revision ID: d8a4a60e8710
Revises: d0f07e8c0bd1
Create Date: 2023-12-27 07:55:01.350943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8a4a60e8710'
down_revision = 'd0f07e8c0bd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interventions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interventions', schema=None) as batch_op:
        batch_op.drop_column('version')

    # ### end Alembic commands ###
