"""average longitude and latitude

Revision ID: dd940d020386
Revises: 7636d6cc574c
Create Date: 2024-03-13 08:09:43.494655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd940d020386'
down_revision = '7636d6cc574c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interventions_values', schema=None) as batch_op:
        batch_op.add_column(sa.Column('average_latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('average_longitude', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interventions_values', schema=None) as batch_op:
        batch_op.drop_column('average_longitude')
        batch_op.drop_column('average_latitude')

    # ### end Alembic commands ###
