"""status

Revision ID: ea1903bf5260
Revises: 8f8a84aa4229
Create Date: 2024-02-28 08:08:15.814665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea1903bf5260'
down_revision = '8f8a84aa4229'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interventions_values', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_interventions_values_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interventions_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interventions_values_status'))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
