"""custom_fields_values

Revision ID: eabdb3e50a6b
Revises: 3ad12a0e6acc
Create Date: 2024-03-22 11:19:48.182487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eabdb3e50a6b'
down_revision = '3ad12a0e6acc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interventions_values', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dict_of_custom_fields_values', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interventions_values', schema=None) as batch_op:
        batch_op.drop_column('dict_of_custom_fields_values')

    # ### end Alembic commands ###
