"""config_text template_text

Revision ID: f2117fffebb9
Revises: 0c53d5019d2f
Create Date: 2024-01-19 15:49:55.798229

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f2117fffebb9'
down_revision = '0c53d5019d2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('types_interventions_organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('template_text', sa.Text(), nullable=True))
        batch_op.drop_column('config_text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('types_interventions_organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('config_text', mysql.TEXT(), nullable=True))
        batch_op.drop_column('template_text')

    # ### end Alembic commands ###
