"""site's dict of lists

Revision ID: f2d60458ed68
Revises: 4543b7f0deb5
Create Date: 2024-02-07 14:36:21.356936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2d60458ed68'
down_revision = '4543b7f0deb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dict_of_lists', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_column('dict_of_lists')

    # ### end Alembic commands ###
