"""refactoring

Revision ID: f86bd8e82086
Revises: b994476983fe
Create Date: 2023-12-31 00:11:01.689150

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f86bd8e82086'
down_revision = 'b994476983fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intervention_id', sa.String(length=36), nullable=True))
        batch_op.drop_constraint('fields_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'interventions', ['intervention_id'], ['id'])
        batch_op.drop_column('form_id')
        batch_op.drop_column('average_latitude')
        batch_op.drop_column('average_longitude')

    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intervention_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(None, 'interventions', ['intervention_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('intervention_id')

    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('average_longitude', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('average_latitude', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('form_id', mysql.VARCHAR(length=36), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fields_ibfk_1', 'forms', ['form_id'], ['id'])
        batch_op.drop_column('intervention_id')

    # ### end Alembic commands ###
